### ISSUE TITLE
Affichage du layout

### ISSUE THREAD

**Issue by axelvaindal** [axelvaindal/Yggdrasil#4]
Corriger les fichiers CSS et les templates de façon à ce que le container contenant la structure générale du projet est une taille plus logique que la taille actuelle, et s'assurer de la responsivité. A noter que la topbar n'est pas responsive en version mobile, ce qui est un comportement normal.

Ajouter une média query pour afficher un template spécifique indiquant l'arrivée d'une application mobile lorsque l'on atteint la taille d'un mobile.

Edit:  Les formulaires de register et de login ont un comportement un poil trop margé par rapport au top sur des écrans plus petit (exemple mon laptop), réduire la marge top sur ces deux templates.

Prendre en considération les tailles d'écrans jusqu'au mobile (non pris en charge), et vérifier la structure de base ainsi que les templates existants et corriger le cas échéant.

Ouvrir un document sur le drive indiquant la compatibilité de la plateforme par rapport au navigateur (à mettre à jour en temps réel). Notre objectif est une compatibilité Chrome, Firefox, Safari et IE10+.

Préparer un template d'affichage en cas de navigateur non pris en charge (indiquant de mettre à jour et bloquant l'accès au site).

Ouvrir un document sur le drive indiquant la compatibilité des librairies utilisées sur la plateforme par rapport au navigateur (meteor list pour afficher la liste des packages et des versions).

**Comment by axelvaindal** [comment]
@remiHau : Tu peux pull le master et créer une branche chez toi pour cette issue lorsque tu auras installé ton linux. J'ai testé sur Ubuntu 15.04 ca fonctionne, hormis les bugs d'affichage cité ci-dessus constaté sur Firefox sur un écran laptop.

**Comment by remiHau** [comment]
En attendant qu'on définisse un template pour l'affichage en version mobile, je remodifie les problèmes suivants : formulaires et compatibilité navigateurs.

**Comment by remiHau** [comment]
La documentation reste à faire. Le reste a été pris en charge.
J'ai déjà pu tester Edge, FF, chrome, et IE 10&11. Aucun problème à signaler.
Reste à établir le document et faire les test pour safari, opera & chromium.

**Comment by axelvaindal** [comment]
Il y a des soucis d'affichages lors du redimensionnement de la fenêtre.

Sur les pages fullscreen, on voit le menu dépasser en bas si on scroll.
Sur la sidebar, si on scroll trop, le fond blanc n'y est plus, et il reste juste le menu ce qui fait un peu sale.

Ici le scroll en fullscreen : 

![screenshot from 2015-08-30 22 44 44](https://cloud.githubusercontent.com/assets/11026659/9569371/46fdbca0-4f69-11e5-8896-48125a9a225b.png)
Ici le problème de menu quand la hauteur est faible : 

![screenshot from 2015-08-30 22 50 22](https://cloud.githubusercontent.com/assets/11026659/9569379/8f9246e8-4f69-11e5-991e-b94daf03e1d0.png)

J'ai pas testé pour le navigateur IE 10 + mais je te crois sur parole pour ca, refais des tests avec les deux configurations au dessus pour être sur quand même :)

**Comment by axelvaindal** [comment]
Oh, et il faudrait peut être mettre un scroll en plus juste pour la barre, celle ci ayant un contenu dynamique en fonction de l'utilisateur, notamment à cause de la section Games, ca réglerait surement le bug en plus d'être peut etre plus ergo pour l'utilisateur.

**Comment by axelvaindal** [comment]
@remiHau Après reflexion, je me rends compte que il y a peu de place pour le contenu à cause de toutes ces barres ,alors on va refactoriser un peu : 

- La sidebar ne doit s'afficher que lorsqu'on est connecté, et a les options suivantes (Dashboard, Mes jeux, Support, Mon Compte ainsi que les infos basiques sur le compte), la police est plus petite, pour donner l'impression de prendre moins de place et elle peut être réduite vers la gauche de l'écran. 

- La topbar affiche la gestion de la langue, les notifications, les messages, la base de connaissance, et les jeux publics. Aussi un bouton register/login lorsqu'on est pas co à la place des notifications et messages, faut voir pour trouver un design sympa pour cela.

On conserve le container que tu as mis qui est top il devrait avoir plus d'impact comme cela.
Après cela, on ne change plus rien, on aura le design tranquille pour mettre le contenu et le code.

Je te laisse sur cette issue, en attendant je m'occupe de l'internationalisation pour te réduire un peu le travail. Après ça, on découpe les fonctionnalités de notre espace admin et go ! :)

**Comment by axelvaindal** [comment]
TODO:

- Réduire la marge à gauche sur la sidebar
- Retirer les effets active (etc) sur les liens (vieux contours bleu dégueu)
- Redimensionner le bloc logo pour qu'il ait la taille de la sidebar
- Déplacer le bouton toogle
- Rajouter le vrai bloc information
- Rajouter les liens vers les vues sur la sidebar (#pathFor)
- Virer l'animation sur le drapeau
- Ajouter l'onglet BDC et Games
- Mettre le bloc register/login quand pas connecté à la place de notification et message
- Faire en sorte que le contenu suive la taille disponible à l'affichage (lors du redimensionnement)
- Mettre le hover en tant qu'effet sur le lien actif sur la sidebar
- Afficher un bouton de déconnexion quand l'utilisateur est log.

Une fois fait et validé, ajouter les templates, clean le code obsolete, refaire un tour sur le nommage des routes et merge sur le master.

**Comment by remiHau** [comment]
Pour le problème 3, je préfère attendre, j'apprécie le positionnement du toggle actuel, à discuter ensemble. Pour le problème 6, il manque beaucoup de routes et je préfère qu'on voit l'archi ddes routes ensembles
